language: php

php:
  - 5.5
  - 5.6

install:
  - composer self-update && composer install

before_script:
  # Disable xdebug. NB: this should NOT be done for hhvm...
  - if [ $TRAVIS_PHP_VERSION != "hhvm" ]; then phpenv config-rm xdebug.ini; fi

script:
   php vendor/bin/phpunit
